### ISSUE TITLE
Add languages implemented by Kattis

### ISSUE THREAD

**Issue by jsannemo** [Kattis/problem-package-format#102]
The following languages are supported by Kattis, but not listed among the languages. It would be good to standardize their codes, extensions etc:

APL
Bash
COBOL
Dart
F#
Fortran
Gerbil
Julia
TypeScript
Visual Basic

@niemela could you take point on that?

**Comment by niemela** [comment]
> @niemela could you take point on that?

Will do!

**Comment by jsannemo** [comment]
(I thought I was pretty well-acquainted with languages, but I have never heard of what this "Gerbil" is)
