### ISSUE TITLE
Test data settings in `testdata.yaml` and inheritance

### ISSUE THREAD

**Issue by thorehusfeldt** [Kattis/problem-package-format#113]
How are test data settings inherited?

Currently we have the following explanations. In `legacy`,

> In each test data group, a file testdata.yaml may be placed to specify how the result of the test data group should be computed. If a test data group has no testdata.yaml file, the testdata.yaml in the closest ancestor group that has one will be used. If there is no testdata.yaml file in the root data group, one is implicitly added with the default values.

At my behest, we changed this slightly in `2023-07-draft`.

> […] If a test data group has no testdata.yaml file, the testdata.yaml in the closest ancestor group that has one will be used. If there is no testdata.yaml file in the root data group, one is implicitly added with the default values.

Alas, with the significant changes @jsannemo is proposing for the scoring/grading framework (see https://github.com/Kattis/problem-package-format/blob/master/spec/2023-07-draft.md#grading) , this is no longer good enough.

For instance, if `secret/group1/testdata.yaml` does not exist then  then its default value of `grading/aggregation` becomes that of its parent (by the above rule), which is `sum`. But the specification gives `min` a default of `grading.aggregation`. This is at best confusing, at worst gives unintended behaviour.

# Solution 1: wordsmithing

It may be possible to introduce super-precise wording for inheritance or “what default means” that ameliorates this problem. I am not too confident, however.

# Solution 2: different inheritance rules for validator flags and grading/scoring

The rule could be that validator flags _are_ inherited (useful) but grading flags aren’t (also useful). That’s much easier to communicate (and implement.)

# Solution 3: Separate files

3a. Validator flags and grading flags play very different roles, and neither is well-named by `testdata.yaml`. So why not drop `testdata.yaml` and instead use `validator_flags.yaml` and `scoring.yaml`. The intent is very clear, the rules could be very clearly explained, and ICPC-focussed tools and judges can completely ignore `scoring.yaml`.

3b. If it’s worth doing, it’s worth doing right:
* `input_validation.yaml` contains input validator flags. It’s useful for _construction_ tools like `problemtools` and `BAPCtools`. They don’t even need to be exported to a judge.
* `output_validation.yaml` contains output validator flags. In ICPC-traditions, it only appears in at toplevel `data`. Important for _judging_.
* `scoring.yaml` is as above. Important for judging, but only for `type:scoring`. DOM-judge never touches this.

Clean, obvious, easy to describe, easy to maintain, good separation.

**Comment by Tagl** [comment]
I definitely prefer 3b over 3a, like you say, if we're gonna separate them we should truly separate them based on their use cases.

**Comment by niemela** [comment]
I don't think splitting this out in 3 files is reasonable. Mostly because there would only be one value to set in either of `input_validation.yaml` and `output_validation.yaml`.

It seems very reasonable to me to instead collect the settings that relates to the test data in `testdata.yaml`.

Regarding inheritance, I agree that it's currently very unclear. I think the "wordsmithing" option is the way to go.

**Comment by thorehusfeldt** [comment]
My suggestion is that

* values for the keys `run_samples`, `input_validator_flags` and `output_validator_flags` _are inherited_ from ancestral `problem.yaml`
* values of `grading.min` and `grading.foo`  _are not inherited_ (instead, the  default in the specification kicks in.)

**Comment by thorehusfeldt** [comment]
Summary of meeting 2023-01-15:

`problem.yaml` contains _flags_ that define, on a per-directory basis, the behaviour of validators and grading. The keys are `input_validation`, `output_validation` and `grading`. 

```cue
#testdata: {
    input_validation: string | { [#filename]: string }
    ouput_validation: string
    grading: close({
        max_score?: >= 0
        score?: >= 0
        aggregation?: "sum" | "min"
    })
}
#filename :=~ "^[a-zA-Z0-9][a-zA-Z0-9_.-]*[a-zA-Z0-9]$"
```

Inheritance shall be carefully specified; it goes by key for the `validation` flags; flags are not cumuiative. `grading` flags are not inherited.
