### ISSUE TITLE
Included code vs included files

### ISSUE THREAD

**Issue by Tagl** [Kattis/problem-package-format#114]
Imagine I have a task where I, for example, want to provide a text file which contains the names of all countries in the world.
The program should read the file to learn the names, then filter out some countries based on suffix or something like that.
Well you don't have to imagine, I do have a task like that which I need to set up 😄
How would I go about doing this now?
I'd probably use `include`, provide a main file which writes the file and then execute the submitted file, seems hacky to me.

Currently `include` is used to include code files alongside submissions.
If I add files to `include/prolog` then all `*.pl` files within the directory will be included for Prolog submissions.
I think this is not the behavior we want, at least it is not the behavior I want nor expect.
What I expect it to do is: include *all* files that are placed in the directory with each submission in the specified language.
Bonus if we have an `include/all` which is used for covering all languages, specifically useful when providing generic files that are unrelated to the language of choice.

Order of operations before running a submission:
1. Place submitted files in a submission directory
2. Place files from `include/all` in the submission directory, overwrites existing files
3. Place files from `include/<language>` in the submission directory, overwrites existing files

I think this is the most flexible way to have files included in general.

Note: This does relate a bit to the `.files` discussion but this is more useful in the case where files are used in all testcases, not on a per testcase basis. In that case, files within `.files` would be place in submission directory as the fourth and final step, also overwriting existing files. Tagging @niemela since he proposed that feature.

**Comment by niemela** [comment]
> Currently `include` is used to include code files alongside submissions. 

Correct, "included code" is *intended* for code.

> If I add files to `include/prolog` then all `*.pl` files within the directory will be included for Prolog submissions. 

That's not what the current (very short) spec says though. It says that all files will be copied.

> I think this is not the behavior we want, at least it is not the behavior I want nor expect. What I expect it to do is: include _all_ files that are placed in the directory with each submission in the specified language. 

Agreed. (And that's what it currently says).

> Bonus if we have an `include/all` which is used for covering all languages, specifically useful when providing generic files that are unrelated to the language of choice.

Agreed. In fact, that was the originally the intent, I actually thought that's what the spec says, but it isn't.

> Order of operations before running a submission:
> 
> 1. Place submitted files in a submission directory
> 2. Place files from `include/all` in the submission directory, overwrites existing files
> 3. Place files from `include/<language>` in the submission directory, overwrites existing files

4. Place files from `<testcase>.files` in the submission directory, overwrites existing files

> 
> 
> I think this is the most flexible way to have files included in general.

Agreed.

> Note: This does relate a bit to the `.files` discussion but this is more useful in the case where files are used in all testcases, not on a per testcase basis. In that case, files within `.files` would be place in submission directory as the fourth and final step, also overwriting existing files. Tagging @niemela since he proposed that feature.

Exactly.

**Comment by Tagl** [comment]
> That's not what the current (very short) spec says though. It says that all files will be copied.

Where does it say all the files? I see "the files" which I could take to mean all the files, but it is right after mention of included _code_, which was unclear enough for me. My original confusion came from the problemtools implementation, which only copied the language's source files.

But it seems we at least have a consensus on this. I'll write up a PR for this.

**Comment by niemela** [comment]
> Where does it say all the files? I see "the files" which I could take to mean all the files, but it is right after mention of included _code_, which was unclear enough for me. 

Yes, I agree that it's less clear than it could be.

I think the proper fix is:

- Rename section from "Included Code" to "Included Files"
- Add specification of the `all` "language", and specify the semantics for what happens when you have specified both `all` and some other specific language. I think there are two reasonable options:
  - `all` is copied first, and `<language>` is copied after, possibly overwriting. I.e. what you suggested.
  - `all` is only copied if no `<language>` is specified for the language in question. I.e. `all` actually means "all others".

**Comment by Tagl** [comment]
The other reasonable option is probably more convenient in general.
Perhaps `default` would be a more apt name in that case than `all`.

**Comment by Tagl** [comment]
Lets consider the case where you'd have a non-empty `all` directory and then an explicitly empty `cpp` directory.
That seems like it may be an issue with the second option.

**Comment by niemela** [comment]
> Lets consider the case where you'd have a non-empty `all` directory and then an explicitly empty `cpp` directory. That seems like it may be an issue with the second option.

Why is that an issue? that would copy the files in `all` for all submissions except submissions in C++, which is what would seemingly be intended?

This is in fact an example of the fact that the second option is strictly more powerful than the first. There is no way to include a file for every submission *except* for submissions in a given language using the first option. I can think of some use cases where a file is needed for every language *except* some set of languages, but I can't think of any use case where it's also *important* that that file is *not* provided to the languages that don't need it.

**Comment by Tagl** [comment]
The issue is that empty directories are often ignored by tools, and a notable example of this is git.
This can be bypassed then by just adding some dummy file in the directory.
That was my main concern, sorry for not clarifying.

I do agree that it is strictly more powerful and a better option therefore IMO.

**Comment by RagnarGrootKoerkamp** [comment]
I suppose that
* `default` hints slightly more at `copy this unless a language specific directory is present`
* `all` hints more at `always copy this, unless overridden by a specific language`

Both are fine, but I think always copying is slightly simpler conceptually. Having a few extra files doesn't really sound like it could hurt, and prevents one from copying/symlinking a file into all the language-specific directories manually.
