### ISSUE TITLE
Should included code count towards code limit?

### ISSUE THREAD

**Issue by Tagl** [Kattis/problem-package-format#115]
Should it?
I'm leaning towards no.
Reason being that it is code provided by the authors of the problem, so it should not impact the submitter.
There can also be a great difference between the size of provided Java code vs size of provided Python code because Java standard library has a much wider variety of built in data structures.

**Comment by niemela** [comment]
I would also lean no (for pretty much the same reasons).

In any case, it should be made clear if it does or not.

**Comment by Tagl** [comment]
Problemtools currently does count included code, and I imagine Kattis does too then.

**Comment by niemela** [comment]
I think that either choice is "logically coherent". But it should be made clear.

> Problemtools currently does count included code

Then I might actually lean the other way (i.e. to keep thet status quo). I don't see a very strong argument for either choice, and then I think "whatever we currently do" is  good :).

**Comment by Tagl** [comment]
Well I definitely think what is currently done is the less logical choice, simply from the reasons stated above, but it's easy to bypass any issues in each problem by raising the limit and I don't think it has a big negative effect to do so.

**Comment by niemela** [comment]
> Well I definitely think what is currently done is the less logical choice, simply from the reasons stated above, 

I don't think it's less logical, it's just a different logic.

The logic that brings you to the current way is that you think about "the submission" as what the user sends in with the included copied into (in fact, that's pretty much how it's described).  What is good about thinking about it this way is that the judging system does not have to know about included code at all, it's just a preprocessing step.

Actually, when you think about it the other limits work just the same. If the included code is using a lot of time or memory, that is not deducted from what is used by the submission as a whole, and it would in fact be hard to do so. So, maybe it's actually *more* logical to have the code size limit behave as all the other limits?

> but it's easy to bypass any issues in each problem by raising the limit and I don't think it has a big negative effect to do so.

That is certainly also true...

**Comment by Tagl** [comment]
> Actually, when you think about it the other limits work just the same. If the included code is using a lot of time or memory, that is not deducted from what is used by the submission as a whole, and it would in fact be hard to do so. So, maybe it's actually _more_ logical to have the code size limit behave as all the other limits?

That is a very good point.

**Comment by eldering** [comment]
I think that from a technical (judging system) point of view counting only team code towards the limit makes more sense. As already mentioned, the origins of the code are different and they might be combined at any point in time. For example in DOMjudge that would be on the judgehost when creating the sandbox to run the submission. OTOH, the source code limit may be enforced (well) before that, again in DOMjudge when you submit. That means that for us it would entail a big overhaul of the system to support a limit on the combined team+jury code. Also, currently we can just reject the submission if it is too large. In the other case, one would likely have to add a judging verdict.

Finally, as a contestant I can measure my own code size, so known whether I'm within limits, but can't do that with the jury provided code, unless of code its size is specified, which I think is slightly awkward and easy to forget.

**Comment by simonlindholm** [comment]
> For example in DOMjudge that would be on the judgehost when creating the sandbox to run the submission. OTOH, the source code limit may be enforced (well) before that, again in DOMjudge when you submit. That means that for us it would entail a big overhaul of the system to support a limit on the combined team+jury code.

This is true for Kattis too. I don't think it's worth the effort for change this, for unclear benefit.

**Comment by niemela** [comment]
> I don't think it's worth the effort for change this, for unclear benefit.

I strongly agree with this sentiment...

It seems to me that there are plenty of very good arguments for both choices. (And not really any arguments *against* either). In other words, I think either choice will be good, we should just pick whatever makes life easier for us.

**Comment by Tagl** [comment]
> This is true for Kattis too. I don't think it's worth the effort for change this, for unclear benefit.

Does this mean Kattis and DOMJudge both check the size on submission, and not after copying the include directory?
Then all we have to do is clarify that is the way it should be?

**Comment by nickygerritsen** [comment]
> > This is true for Kattis too. I don't think it's worth the effort for change this, for unclear benefit.
> 
> Does this mean Kattis and DOMJudge both check the size on submission, and not after copying the include directory? Then all we have to do is clarify that is the way it should be?

DOMjudge [does](https://github.com/nickygerritsen/domjudge/blob/a697162529721ea12a7e72527cd347c225a0b151/webapp/src/Service/SubmissionService.php#L551-L551) (although we only check against our global config variable, though it shouldn't be hard to check a problem specific limit).
