### ISSUE TITLE
What languages should be supported for validators

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#122]
In the current spec it's strongly implied (but not explicitly stated) that submissions, input validators, and output validators can be written in *any* language (or at least any language from a very long list of languages, that is being made even longer by #119).

I definitely don't think that we want to require that every system can compile and run programs in every language.

For input and output validators I think we should limit the set of languages that can be used to something fairly small, and that we *should* require compliant systems to support those languages. This set should definitely include C++ and Python (and maybe C?). Does it need to include anything else?

For submission we actually do want to allow problem authors to include solutions in any language, but we should specify how a problem package could be used even if some languages used are not supported?

**Comment by Tagl** [comment]
My guess is there are quite a few validators written in Java, not nearly as many in C++ and Python though.
Can you check for that on Kattis?

Additionally, build and run scripts can be used so I guess technically you can do anything?
We shouldn't remove the build/run option for validators at least.

**Comment by thorehusfeldt** [comment]
Genuine question: When Kattis judges a solver submission, does it input-validate the testdata?

**Comment by niemela** [comment]
input validators:
- Python: 2386
- CTD: 1710
- C++: 559
- VIVA: 446
- Java: 226
- C: 13 
- Ruby: 2
- C#: 2
- Haskell: 1
- Maple: 1

Output validators:
- C++: 428
- Python: 118
- C: 2
- Java: 1

Based on this I would be very happy to limit input validators to Python, C++, Java (in addition to CTD and VIVA), and output validators to Python, C++. And honestly, I would kinda like to srop Java as well from the first group.

**Comment by niemela** [comment]
> Genuine question: When Kattis judges a solver submission, does it input-validate the testdata?

I'm not sure what you mean by *solver* submission, but Kattis validates the input at install only.

**Comment by Tagl** [comment]
> Based on this I would be very happy to limit input validators to Python, C++, Java (in addition to CTD and VIVA), and output validators to Python, C++. And honestly, I would kinda like to srop Java as well from the first group.

Is there some complication with Java that makes you want to remove it?
I could see people opting for it due to the rich standard library.
I have a negative amount of love for the language and don't mind removing it personally.

Also what about the number of build/run validators? I know there is at least one that is recently added.

**Comment by thorehusfeldt** [comment]
_solver_ submission as opposed to a submission in `<problemname>/submission`, which I’ll call _author_ submission now.


Thanks for the answer. So as far as I understand, there are at least three different moments where “a validator” is run.

1. During _problem construction_, input and output validators run against test cases and _author submissions_. This happens on local machines or in docker images, possibly (but not necessarily) orchestrated by `BAPCtools` or `problemtools`.
2. During problem installation, a judge system input-validates the testdata and _possibly_ runs the output of _author_ submissions against a validator. The runtime environment is defined by the judging system, such as DOMjudge or Kattis. For instance `closestpair2` can have been installed on Open Kattis is 2013, and was _then_ run against whatever Python, LaTeX, and C++-compilers installed on Kattis.
3. During _judging_, the judging system _today_ runs output validator (but not input validators) against _solver_ submissions using whatever compilers are current.

These seem very different to me.

**Comment by niemela** [comment]
Graders (not really that important since we have dropped them):
- Python: 112

Submissions (not really that important since we will not limit them):
- C++: 12648
- Python: 5547
- Java: 4469
- C: 886
- C#: 144
- Haskell: 78
- Kotlin: 47
- Go: 23
- Rust: 22
- Pascal: 14
- Perl: 14
- PHP: 8
- Ruby: 8
- JavaScript: 7
- Scala: 2
- COBOL: 2

**Comment by niemela** [comment]
> _solver_ submission as opposed to a submission in `<problemname>/submission`, which I’ll call _author_ submission now.

Funny story. What you call _solver_, we actually internally call _author_. The reason for this is that that is the terminology used by the Valladolid online judge back in the days. In retrospect, I think this was our second worst naming error (that we're still stuck with). 

> [...]
> These seem very different to me.

Yes, indeed.

Use case 1 is as you say *mostly* run locally, and when that's the case there is nothing to worry about. You would naturally *have* all the languages that you're using, and you would also have the exact same version as yourself. That said, even for this use case there is a shared variant. If you are working as a group on a problem set you would be running programs checked in by others, and you might also be running these validation as part of some CI.

**Comment by niemela** [comment]
> Is there some complication with Java that makes you want to remove it? 

Yes, I would love to not have to support Java.

> I could see people opting for it due to the rich standard library. I have a negative amount of love for the language and don't mind removing it personally.

Same.

> Also what about the number of build/run validators? I know there is at least one that is recently added.

2 build scripts, and 3 run scripts.

**Comment by eldering** [comment]
I'm fine with the proposed languages for input/output validators and would also happily drop Java.

Also, given the support with build/run scripts, you can always support other languages implicitly as long as the compiler tooling is installed. Of course this requires some coordination between problem creator and admin of the CCS where the problem gets installed.

**Comment by niemela** [comment]
> I'm fine with the proposed languages for input/output validators and would also happily drop Java.

:+1:

> Also, given the support with build/run scripts, you can always support other languages implicitly as long as the compiler tooling is installed.

That's true. I was kinda hoping that we could drop the build/run scripts, but you think that they are needed, right?

> Of course this requires some coordination between problem creator and admin of the CCS where the problem gets installed.

Yes, but doesn't "requires some coordination" basically mean that the package is simply not portable?

**Comment by Tagl** [comment]
> That's true. I was kinda hoping that we could drop the build/run scripts, but you think that they are needed, right?

I definitely like having that option for the edge cases. I have used it at least once that I can remember and the alternative in that case would have been very painful and time consuming, although doable.

**Comment by niemela** [comment]
> > That's true. I was kinda hoping that we could drop the build/run scripts, but you think that they are needed, right?
> 
> I definitely like having that option for the edge cases. I have used it at least once that I can remember and the alternative in that case would have been very painful and time consuming, although doable.

Would you mind elaborating on what that use case was?

@eldering I think you also said you had use cases where this is needed? Do I remember that right? If so, could you also elaborate? Or was it @RagnarGrootKoerkamp ?

**Comment by Tagl** [comment]
I actually showed it to you last weekend when we discussed this shortly.
In the problem [Flæðasmíði](https://open.kattis.com/problems/flaedasmidi), the problem of constructing an output validator is much harder than the task itself, at least if you want it to run reasonably fast.
Our original implementation for the validator was not numerically stable, as demonstrated by one tester submission.
We decided that using the Eigen C++ library was the smart choice here as we needed to solve `Ax = b` for a sparse matrix `A`, a vector `v` and a vector `b`.
Of course, we *could* have implemented all of this ourselves, but it would have been very time consuming and Eigen is quite well tested and efficient.

**Comment by niemela** [comment]
It seems there is actually consensus for limiting languages allowed as follows:
- Input validators: C++, Python. (but also CTD and VIVA)
- Output validators: C++, Python.
- Example submission and included files: no limit.

There is no consensus to remove build and run scripts.

Also, note that as long as we keep the build and run scrips you can actually use any language (or library) that can be included in the package.

I'll try writing a PR implementing this.
