### ISSUE TITLE
Make UUID required

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#124]
Should we make UUID required?

It's one of those things that where:
- It's actually kinda useful for tooling downstream (i.e. problem archives and online judges) if it's actually used.
- It's not that useful at all for the people that would have to add them (i.e. authors).
- It would be very easy for tooling to generate and prefill UUIDs for users.
I.e. it could add some value to make it required?

Alternatively we could make the "recommended" (which doesn't really mean anything, but could probably help just as much as requiring them), and make sure that all "our" tools generate them.

We could also have the ICPC Problem Archive "require" them internally. Which both means nothing, because we would just have (internal) tooling that adds UUIDs when they are missing, so no-one else would have to do anything, and kinda useful, because it would create a public catalogue of UUID to known problem mappings.

Thoughts?

**Comment by RagnarGrootKoerkamp** [comment]
I'm fine adding them by default in `bt new_problem`. No strong opinion on whether the spec should require them -- I don't see that much use for it for myself.
