### ISSUE TITLE
Specifying entry point

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#132]
In the list of programming languages we define "default entry points" for some languages. The fact that we talk about a *default* entry point implies that an entry point could be defined somehow. We don't ever touch on this in the spec. some systems have in the past used rules do detect or decide on the entry point, others (e.g. Kattis) allows the user to specify. This UI detail is an implementation detail and we don't have to specify it, *but* I think we do need to specify it for submissions and included files in the package.

So, what is a good way to specify an override for default entry point for submissions or included files? One obvious solution would be to have some yaml file, say `submission.yaml` with a single key `entry-point` to specify this value. It's a bit awkward, but the default value requires no file and would be the most common by far. It also implies that you can't include a file called `submission.yaml` (at least not for languages that needs an entry point), but that seems like a very minor issue.

Thoughts?

**Comment by niemela** [comment]
I'm leaning quite strongly towards piggybacking this on the "expectations" framework (see #135).

Specifically, add a `entrypoint` property to the "filename globs" in the YAML file of the expectations framework, and call that file `submissions.yaml` (due to the now extended use):

```yaml
# submissions.yaml
accepted/sol2:
   endpoint: main2.py
```

Thoughts?

**Comment by Tagl** [comment]
Is that intentionally `endpoint` or is it a typo?

**Comment by niemela** [comment]
I'll delete the typo comments from the thread to keep it clean...

**Comment by meisterT** [comment]
Sounds reasonable to me. If we end up doing this, we might also add the option to include an author per submission.
