### ISSUE TITLE
Add visualizers

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#138]
*Reply to a comment in #5*
> This is mostly for [...] and visualizers

@RagnarGrootKoerkamp :
"visualizers" is a BAPCtools extension, right?

If yes, could you link to or describe how they are specified there?

**Comment by niemela** [comment]
> or alternatively passing it on `stdin`.

That would be more similar to how the output validator works, which I think is a good thing.

In fact, an obvious alternate design would be to have the output validator be this program, by allowing it to create these files in the feedback directory. The only downside I can think of right away is that this makes it a lot less clear whether there *is* a visualizer or not. I assume that this is something that you have thought about, are there other reasons why that would be worse?

**Comment by Tagl** [comment]
I tend to do
```
./visualizer testcase.ans testcase.png <  testcase.in
```
to visualize testcases as I generate them.
I never considered doing it for team submissions.
I think that's a great idea, but it is a bit of different thing since then you can't use the feedback directory directly.
I would then do it like
```
./visualizer testcase.in testcase.ans testcase.png < testcase.out
```
so I could call it easily when generating and it's easy to specify the image file into the feedback folder.

So I guess another downside is that if this is the output validator it's not as useful, or at least easy to use, when generating data files, I think.

**Comment by niemela** [comment]
> I think that's a great idea, but it is a bit of different thing since then you can't use the feedback directory directly.

Sorry, why can't you use the feedback directory directly?

**Comment by Tagl** [comment]
> Sorry, why can't you use the feedback directory directly?

When generating a testcase, would you specify `secret/group1` as the feedback directory then? Or some other directory? I could move the image file from the feedback directory to the appropriate group I guess.

**Comment by niemela** [comment]
> When generating a testcase, would you specify `secret/group1` as the feedback directory then? Or some other directory? I could move the image file from the feedback directory to the appropriate group I guess.

You could do either of those things. We don't specify where a the feedback directory should be, only that it must exist and be provided to the validator.

**Comment by RagnarGrootKoerkamp** [comment]
I don't like specifying testcase.png as an argument, since that requires
knowing the right extension. We often mix SVG and PNG.

**Comment by niemela** [comment]
@RagnarGrootKoerkamp or @Tagl Would you be able to write up a draft PR for this?

**Comment by RagnarGrootKoerkamp** [comment]
For output, I prefer if they write to some directory, and any file extension types recognised by the tooling are taken as visualizations.

So some options:
1. `visualizer path/to/testcase`, using current working directory for input and output files
2. `visualizer path/to/testcase.in path/to/testcase.ans path/to/output_dir`
3. `visualizer path/to/testcase.in path/to/output_dir < testcase.in`

Since we currently use option 1 that would be my preference but I don't care too much. @mzuenni @mpsijm any thoughts?

**Comment by Tagl** [comment]
> 3\. visualizer path/to/testcase.in path/to/output_dir < testcase.in

The first argument is intended to be .ans right?

**Comment by niemela** [comment]
I'd vote for 2 (for simplicity 😄), since that's the same format as for the output validators.

> Also, we should confirm that we want `visualizers` as the top level directory where they live, so that `visualizers/visualizer/*` is used for multi-file programs. (An alternative is to just make it `visualizer/*` as a single top-level program.)

Agreed. Again, I would prefer if all the different kinds of programs we support work as similar as possible.

> [...] We'd probably need to move those options into `testdata.yaml` files.

Agreed.

@RagnarGrootKoerkamp Would you feel up to writing a PR (draft?) for this?

**Comment by niemela** [comment]
We (@Tagl @eldering @evouga  @JoelNiemela @niemela) had a discussion. @evouga will write up a PR, but this is the quick summary:

- The visualizer will have the same interface as output validators.
- The visualizer will be run right after the output validator and given the same feedback directory.
- The output files from the output validator are used before running the visualizer (not sure if this is important, because...) but the visualizer should not change these files.
- After running (in the multi-pass case, after running all the cases) the visualizer is expected to have produced `teamimage.{png, svg}` and/or `judgeimage.{png, svg}` which will be shown to the team and judges respectively.

This allows (at least) the following workflows:
- the output validator actually does all work and outputs the images and the visualizer is a no-op.
- the output validator does some calculations and shares them with the visualizer through some file in the feedback directory, so the visualizer does not have to repeat that work.
- the output validator and visualizer are completely independent.
