### ISSUE TITLE
Add `submission/rejected` directory

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#139]
As mentioned in #17 and elsewhere...

**Comment by niemela** [comment]
See also #87

**Comment by thorehusfeldt** [comment]
In terms of excectations 0.7, I think this would mean

```cue
if _abbreviation == "rejected" {
    required_testcase_verdicts: ["RTE", "TLE", "WA"]
}
```

Note that this definition does not set `with_margin` (I don’t know how to do that; I’m not sure 0.7 is good enough to express intention.) Better people than me should try to clarify what is meant; in particular if a successfully validated submission with `t < timelimit` (i.e., what is called `AC-` in 0.5) is a permitted testcase verdict.

In excectations 0.5 I would have defined
```cue
if _abbreviation == "rejected" {
    required: ["RTE", "TLE", "WA"]
}
```
which would make it clear that we want the `TLE`  verdict to fail with margin (which is the right thing to do, I believe.) Neither 0.6 nor 0.7 allow this, unless I’m missing something.

I think this is an excellent example of something we want to be able to specify! :-)

**Comment by niemela** [comment]
In one of my proposals (the one you based "0.7" on I believe?) this would be:

```yaml
rejected:
   required: ["RTE", "TLE", "WA"]
   used_for_timing: true
```

(I don't really understand why you can't do basically the same thing in 0.7 though?)

There are two downsides with this compared to 0.5:
- It's longer (but not terribly so)
- It's overly restrictive, it would disallow a submission that fails (only) on "RTE" or "WA" between time_limit/ac_margin and time_limit (using what I think is [the latest and/or clearest definition](https://github.com/Kattis/problem-package-format/issues/135#issuecomment-1834050847))

There is one upside:
- It's clearer. Because the "use for timing" is so explicit. This is subjective of course (and is basically the inverse of the "it's longer" downside).

I think the overly restrictive issue is fixable, but we need a better definition that the linked one.

**Comment by thorehusfeldt** [comment]
Consider:

```cue
// 0.7.x
rejected:
   required: ["RTE", "TLE", "WA"]
   used_for_timing: true
```

Further assume `timelimit=1` and `ac_margin=2`.

Unless you give me better semantics for `used_for_timing` than mine (as specified in 0.7), this means that it unexpected for `secret/a` to run in time `.7s`.

**Comment by eldering** [comment]
I very much agree with @RagnarGrootKoerkamp 's analysis, including

> (We could enrich result-per-testcase by running the output validator whenever the submission finished (ie not RTE or aborted TLE), so that AC/WA becomes an independent axis from finished/TLE/RTE, but I'm not in favour of that.)

and finally

> In the end I think required: [WA, RTE, TLE] with use_margins: false is completely fine for me.

So, I'd like to make a bolder statement and say that we can simply forbid using `use_margins: true` while at the same time specifying `required: ["TLE", x]` with x any of the other non-AC verdicts, and that should be perfectly fine as it doesn't prevent us from expressing anything that is very relevant. But I'm happy to hear a counter-example!
