### ISSUE TITLE
Add `data/invalid_output`

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#143]
Similar to `data/invalid_input/*.in`, it would be very nice to have `data/invalid_output/*.{in,ans,out}`.

For each testcase, a `testcase.in` and `testcase.out` **must** be present, and a `testcase.ans` **may** be present.
This then runs the `output_validator` on the given `out` file, which must exit with code `43` (meaning wrong answer). Otherwise it's an error.

cc @mzuenni

**Comment by niemela** [comment]
The `.in` file for an invalid output, must validate as input correctly, right?

Could this be merged with the `invalid_input` directory somehow? (If so probably renaming it to `invalid`? 

Maybe the `invalid_output` logic applies when there is an `.out` and the `invalid_input` logic applies when there isn't.

**Comment by mzuenni** [comment]
Yes, the `.in` file should be valid in this situation.
Bapctools originally handled input and output in the same directory (i.e. just a `bad` directory), but I think two distinct directories is cleaner.

**Comment by thorehusfeldt** [comment]
I am converging to `data/invalid`, which contains invalid testcases (including default answer files.)

Consider the problem add two number with input format
```
4 
1 2
10 11
-1 5
0 0
```
and expected answer
```
3
21
4
0
```
In particular, the answer file must contain `n` many integers; the problem description would tell us this.

Then a tool can now reject an answer file for syntactic reasons, for instance rejecting the following testcase:
```
bad_output_format:
  in: |
    2
    10 11
    -5 4
  ans:
    21
```
(This is not science fiction; BAPCtools’ answer validators do exactly this.)

But for this to work, the answer validator needs access to both `testcase.in` and `testcase.ans`. (Of course, the output validator would need this as well.) 

—

I’m happy to restrict to the file types `data/invalid/**/*.in` and `data/invalid/**/*.ans` (but to make me really happy it should find `testdata.yaml`).

**Comment by thorehusfeldt** [comment]
Here’s my suggestion:

> ### Invalid Testcases

> The `/data`  may contain an `invalid` directory containing testcases that must be rejected by validation. In particular, every `.in`-file in `/data/invalid` must be rejected by at least one input validator. The directory /data/invalid can organised into a tree-like structure similar to `/data/secret`, and contain flags in `testdata.yaml` files that are passed to the validators.

> Unlike `/data/sample` and `/data/secret`, there need not be a `bad-testcase.ans` file for every `bad-testcase.in`. 

> If `bad-testcase.out` file exists, then `bad-testcase.in` and `bad-testcase.ans` must exist, and the `.out`-file must be rejected by the output validator. If `bad-testcase.ans` exists then `bad-testcase.in` must exist.

**Comment by thorehusfeldt** [comment]
Update: a working specification and implementation now exists at BAPCtools, documentation here: https://github.com/RagnarGrootKoerkamp/BAPCtools/blob/master/doc/validation.md

The directory structure ended up like this:
```
data/
  invalid_inputs/
    tc.in
  invalid_answers/
    tc.{in, ans}
  invalid_outputs/
    tc.{in, ans, out}
  sample/
  secret/
```

**Comment by RagnarGrootKoerkamp** [comment]
As Thore wrote above, we have this working now in BAPCtools and are using it for some upcoming contests and it works well! 

What do others think of this? @niemela @simonlindholm

**Comment by Tagl** [comment]
I think it looks good.

**Comment by simonlindholm** [comment]
Sounds great! I'd be slightly inclined to merge invalid_answers/ and invalid_outputs/ because they feel conceptually the same to me and I think I'd have a hard time remembering which is which, and thus have only invalid_outputs/ and say that if you have an output validator you have to provide both .ans and .out, while if you don't you have to provide only .out.

**Comment by simonlindholm** [comment]
Wait, sorry, I shouldn't be responding to GitHub issues minutes before going to bed past midnight... Of course this feature makes no sense for problems without output validator. It would be possible to validate .out files without .ans by having an arbitrary submission in submissions/accepted/ solve it and then use that as .ans; alternatively, a tool (like our olympiad's [testdata_tools](https://github.com/Kodsport/testdata_tools)) could generate missing .ans files that way. I don't know how I feel about using the same file as .ans and .out. I guess it could be fine.

**Comment by RagnarGrootKoerkamp** [comment]
For problems with custom output validators that ignore the `.ans`, you can just provide an empty `.ans` file and it'll be fine.

Note that you could still use `invalid_outputs` when `output_validation: default`, for example to check that a `.out: 1.0` does (not) match against `.ans: 0.9999` with the given precision flags.

**Comment by niemela** [comment]
I believe this was done by #148.

If I'm mistaken please reopen (although, it it's some specific subset missing, please instead create a new issue describing what more we should want to do).
