### ISSUE TITLE
\illustration and “shall” 

### ISSUE THREAD

**Issue by thorehusfeldt** [Kattis/problem-package-format#147]
The specification reads:

https://github.com/Kattis/problem-package-format/blob/af5288b5c21d8a65ace08296ce7aecad8fdefdd2/spec/2023-07-draft.md?plain=1#L282

>  It shall also provide the following commands:
> \problemname{name}, which must be the first line of the problem statement.  […]
> \illustration{width}{filename}{caption},  […]

Really? I don’t think that’s the intention. Instead, the problemname _shall_ be there, the illustration _may_.

**Comment by RagnarGrootKoerkamp** [comment]
I think this is about the latex class file?
- It *must* (seems better to me than *shall*?) provide the \problemname, which *must* be used in every `problem.lang.tex` file
- It *must* provide the \illustration command, which *may* be used in `problem.lang.tex`.

**Comment by thorehusfeldt** [comment]
You’re right. Closing this.
