### ISSUE TITLE
Multipass clarifications

### ISSUE THREAD

**Issue by mzuenni** [Kattis/problem-package-format#149]
Right now the output validator is unable to save state between runs (except by writing it in the `nextpass.in`). However, it would be useful if the validator could save state between runs without the submission beieng able to access it.

Besides that i have a few additional questions on how multipass problems work:

1. how exactly is the validator invoked? `./valdiator <inputfile> <feedbackdir> [args] < <team.ans>`?
2. how should the `judgemessage.txt` be handled? Does the validator append new stuff or does the judging system append all generated files?

**Comment by Tagl** [comment]
I think a directory would be nicer in case some separation is needed.
It does not really add any complexity to have it as a directory.
@jsannemo Do you have some thoughts on this?

**Comment by mzuenni** [comment]
Additional remark: it seems like runtime and memory consumption...? are not yet defined in the spec. As far as I have heard it should be the maximum over all invocations but it should probably be added to the doc.

**Comment by niemela** [comment]
I very much agree that this is currently unclear how information is passed between passes.

I would suggest that we explicitly say that everything written to the feedback directory is kept between passes. This means that the output validator would be responsible to append (or overwrite) the feedback files in any way it sees fit, and would be allowed to create any number of additional files that it needs. The judging system would then always (i.e. both in the single and multi-pass cases) just have one single `judgemessage.txt` or `teammessage.txt` file to handle.

> Additional remark: it seems like runtime and memory consumption...? are not yet defined in the spec. As far as I have heard it should be the maximum over all invocations but it should probably be added to the doc.

Correct, that is the intended meaning, and yes, that should definitely be written in the spec.

What do you think?

**Comment by RagnarGrootKoerkamp** [comment]
What is the reason for making runtime the max over invocations rather than the sum?

This could make an incentive to move some work from the slowest pass to earlier passes to reduce the max? Whereas summing them doesn't make such weird incentives.

**Comment by niemela** [comment]
> This could make an incentive to move some work from the slowest pass to earlier passes to reduce the max? Whereas summing them doesn't make such weird incentives.

I would say that you can make a similar argument in either direction. With sum you are incentivized to "over-optimize" the easier passes to buy more time for the hard one(s).

It feels like the natural parallel to how we handle time limits for multiple test cases. We do max, not sum. And for similar reasons I think it's easier (as a problem setter) to reason about what limit I want for the max, than for the sum.

Also, all the examples of multi-pass problems that I have seen feels more natural as max than sum. 

None, of these arguments are great b.t.w., if you have some examples showing that sum would be better, please share.

**Comment by RagnarGrootKoerkamp** [comment]
I'll be fine with max :)
But still I'm curious for an explicit motivating example -- I don't think I've seen multipass before in practice yet. (A link is fine.)

**Comment by mzuenni** [comment]
For sum you also accumulate the start up times for stuff like jvm so i would also be in favour of max.

**Comment by niemela** [comment]
> I'll be fine with max :) Indeed if you consider separate passes as separate cases `max` makes a lot of sense.

:+1:

> But still I'm curious for an explicit motivating example -- I don't think I've seen multipass before in practice yet. (A link is fine.)

The canonical examples is typically compress/decompress (i.e. "given an input, produce output smaller than X. Given that output, produce the input").

> For sum you also accumulate the start up times for stuff like jvm so i would also be in favour of max.

Yes, that's a better argument. :)

**Comment by niemela** [comment]
@mzuenni Do you feel up to write a PR fr this one?

**Comment by mzuenni** [comment]
@niemela I think we need to make an exception for the `nextpass.in` file? Else a validator would always need to remove this to be able to signal WA?

**Comment by simonlindholm** [comment]
https://open.kattis.com/problems/guessinggame2 is an example of a multi-pass problem we ran for EGOI last year (emulated via include/ files for the languages we supported). That one also comes with an obscure argument for using max instead of sum: multi-pass problems may allow a grader to be adversarial by running the program multiple times to see what it would do, and with sum that's even harder to motivate to contestants. Probably not something that comes up very often though. :)

**Comment by mzuenni** [comment]
One further question, it was said that for non-interactive problems the validator is invoked as
```
./validator <inputfile> <answerfile> <feedbackdir> [args] < <teamoutput>
```
but what exactly is `<answerfile>`? Is it the same for all passes?
