### ISSUE TITLE
Where did grader flags go?

### ISSUE THREAD

**Issue by Tagl** [Kattis/problem-package-format#159]
At a certain point grading was simplified and now verdict aggregation is essentially gone?

So how do we state that the first error should be used?
Or that we accept if anything is accepted?

Are we just assuming this based on the type of the problem?
Because score of 0 does not mean "not accepted" necessarily. (Should it?)

**Comment by Tagl** [comment]
May be solved by #161

**Comment by niemela** [comment]
> May be solved by #161

Not really.

> So how do we state that the first error should be used? 

Currently, you can't.

One could argue that the first vs worst vs (whatever) error should be a system (contest) level property. Does that make sense? If so, this would not be needed.

> Or that we accept if anything is accepted?

This could (maybe?) be done with `aggregation: max`. @evouga (as well as @jsannemo I think) suggests that we should simply ignore verdict for scoring problems, and would you ever want "accept if anything is accepted" for pass-fail?

> Are we just assuming this based on the type of the problem? 

That is basically what #217 says, yes. (Please review it)

> Because score of 0 does not mean "not accepted" necessarily. (Should it?)

No, I don't think it should.

**Comment by niemela** [comment]
@Tagl Is this still an issue after the last few days of updates?

**Comment by Tagl** [comment]
I think not
