### ISSUE TITLE
Handle conflicts with {%name%} style constants

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#176]
Currently the spec says:

> Names must match the following regex: `[a-zA-Z0-9_.-]`.
> *Constant sequences* are tokens (regex words) of the form `{%name%}`.
> The `name` in every constant sequence must be a valid constant name.

I interpret this to mean the following:

- In a prepossessing step we find every string matching `{%([^%]+)%}` (in all the relevant files).
- If any capturing group does not match `[a-zA-Z0-9_.-]*` that's an error (Side note: the first regex above is wrong, right?)
- If any capturing group is not listed as a constant in `problem.yaml` that is... unclear if it's an error.

I think what we actually want is:

> Names must match the following regex: `[a-zA-Z0-9_.-]*`.
> *Constant sequences* are tokens (regex words) of the form `{%name%}`,
> where `name` is one of the names defined in `constants`

This means that conflicts with other tools that use some `{% %}` syntax would not be a problem (for us) as long as we have not defined a constant with the exact name of what's between the `{% %}`. It also means that we can't make misspelled constant names an error (although we could warn).

Thoughts? 

@mzuenni @RagnarGrootKoerkamp

**Comment by RagnarGrootKoerkamp** [comment]
yes, only replacing known constants is fine. That can also be simply implemented using direct string replacement.

Warning for unknown constants also sgtm. That doesn't have to be an error.

**Comment by RagnarGrootKoerkamp** [comment]
Another issue;

In latex `%` starts a comment, so that `{%` opens a block that will never be closed. That's quite annoying for editor highlighting and autoformatting. Maybe `{%..%}` is not the best syntax after all.

**Comment by niemela** [comment]
> In latex `%` starts a comment, so that `{%` opens a block that will never be closed. That's quite annoying for editor highlighting and autoformatting. Maybe `{%..%}` is not the best syntax after all.

Yes, that's a very good point.

Is `{{name}}` better?

**Comment by RagnarGrootKoerkamp** [comment]
Yes, `{{name}}` is a good suggestion.
