### ISSUE TITLE
Multipass samples

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#177]
For multipass we need a new sample format.
How about extending the interaction format:
```
<first round input
<more input
>first round output
---
<second round input
>second round outpu
```
Note that each round could in itself be interactive, so simply alternating `<` and `>` is not sufficient.

Another option could be something like `sample.{in,ans}.1`, `sample.{in,ans}.2`, `sample.{in,ans}.3`, ..., but creating and detecting arbitrary many files feels ugly

**Comment by niemela** [comment]
> How about extending the interaction format:

:+1:

> Another option could be something like `sample.{in,ans}.1`, `sample.{in,ans}.2`, `sample.{in,ans}.3`, ..., but creating and detecting arbitrary many files feels ugly

Yeah, I think that option is less good.

@RagnarGrootKoerkamp Could you write a PR maybe?

**Comment by Tagl** [comment]
Lets extend the interaction format.
