### ISSUE TITLE
Define score.txt (and maybe also judgemessage.txt and teammessage.txt)

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#194]
We should define the format of the `score.txt` file somewhere in the output validator description. Maybe we should do the same with `judgemessage.txt` and `teammessage.txt`? There are no real requirements on their format, but then it makes sense to say *that*.

**Comment by evouga** [comment]
What is the current practice for score.txt? It’s a single line with one integer? Or one float?

**Comment by niemela** [comment]
A related question (so I write it here), do we want to change the name of `teammessage.txt` to e.g. `usermessage.txt`. The format is not only used for contests, so maybe we should not use contest terminology?

I'm leaning towards "no", because it's not actually user visible, and it makes translating from old to new format quite a bit harder (or at least more annoying), for very small gain.

Thoughts?

**Comment by niemela** [comment]
> I'm leaning towards "no", because it's not actually user visible, and it makes translating from old to new format quite a bit harder (or at least more annoying), for very small gain.

Although we could *deprecate* `teammessage.txt` and look for both?

**Comment by Tagl** [comment]
> > I'm leaning towards "no", because it's not actually user visible, and it makes translating from old to new format quite a bit harder (or at least more annoying), for very small gain.
> 
> Although we could _deprecate_ `teammessage.txt` and look for both?

Is the deprecation *ever* going to result in not having to support `teammessage.txt`?

**Comment by evouga** [comment]
`score.txt` is now defined.
