### ISSUE TITLE
Constants: "formatted as described below"

### ISSUE THREAD

**Issue by ghamerly** [Kattis/problem-package-format#199]
In https://github.com/Kattis/problem-package-format/blob/master/spec/2023-07-draft.md
there is the text
```
All constant sequences in the following files will be replaced by the value of the corresponding constant, formatted as described below:
```
but the "formatted as described below" does not make sense to me. What's listed below that statement are files, not formatting directives. Is that clause referring to the text above? Or something else (that perhaps needs to be added)?

**Comment by mzuenni** [comment]
I think  `, formatted as described below` refers to something we removed and should be removed as well?

**Comment by niemela** [comment]
> I think `, formatted as described below` refers to something we removed and should be removed as well?

Yes. #163 is the relevant ticket, and specifically the "Drop the format specifier" part.
