### ISSUE TITLE
Define float (for the default output validator)

### ISSUE THREAD

**Issue by mzuenni** [Kattis/problem-package-format#203]
The spec says that the default output validator tries to compare floats (if a floating point tolerance is given) but does not define what a float is/which representation will be parsed as a float. Consider the following list, what is a float?
```
0
0.0
-0
-0.0
0e1
0E1
0.0e1
00
01
.0
-.0
+0
+0.0
+.0
0e0.1
0x0
0X0
0x0p1
NaN
nan
-nan
-NaN
inf
-inf
infinity
-infinity
-
.
```
most of these would be accepted by functions like c++ `std::stold()` but never get printed by any library.

I would only consider the first 7 as valid floats for the following reasons:

- `+` should not be used as sign
- numbers should not have leading zeros
- numbers should be in decimal not in hex
- floats should not start with a `.`
- special values like `nan` are not numbers... as their name suggests.
- `infinity` regularly comes up as a string that you are supposed to print and should not be equal to `inf`, and the `case_sensitive` flag should affect the equality here.

The definition could be something like this:

An integer is:

- an optional `-`
- followed by digits without leading zeros

A float is:

- an integer
- optionally followed by a `.` followed by any number of digits
- optionally followed by `e` or `E` followed by an integer

Further remark, the `case_sensitive` flag should not affect float parsing i.e. `0e1` = `0E1` even if you pass `case_sensitive`.

**Comment by niemela** [comment]
Side note:
> [mzuenni](https://github.com/mzuenni) changed the title Define float Define float (for the default output validator)

We should probably also define this for the purpose of the value in`score.txt`.

**Comment by mzuenni** [comment]
Are there any other opinions about what floats we want to allow?

**Comment by niemela** [comment]
@mzuenni What you write makes a lot of sense (to me). It worries me a little bit that we have our own definition of such a common concept, is there no definition of floating point numbers we could piggy back on (i.e. refer to).

Do you feel up to writing a PR fixing this?

**Comment by mzuenni** [comment]
I am worried about leading zeros. We would never allow them for integers, right? then it feels weird to allow them for floats (and it's nothing any print function would ever produce anyway). Same for +, we don't allow that for integers either?

**Comment by niemela** [comment]
> We should definitely accept anything that a normal print function could produce (even weird looking stuff like `-0`, `-0.0`)

Agreed. What set of languages and print functions are included in "normal"?

> we should not allow unnecessary stuff (like `+`)

That's a bit of a can of worms though. What do you mean by unnecessary? Scientific notation is never *needed*, it's just much shorter and nicer in some cases. The `-` in `-0` is certainly unnecessary.

> the only additional thing to my original proposal which we maybe should allow is that the leading integer can be empty i.e. allow `.0` and `-.0`. However, right now that would imply that we also allow `.` which was never a valid floating point.

Should we even allow `123.`? That feels more iffy to me than `.123`. We should definitely not allow `.`.

**Comment by mzuenni** [comment]
> Agreed. What set of languages and print functions are included in "normal"?

I tried c++, java and python but i guess most languages behave similar here.

> That's a bit of a can of worms though. What do you mean by unnecessary? Scientific notation is never needed, it's just much shorter and nicer in some cases. The `-` in `-0` is certainly unnecessary.

Mainly stuff that a print function would not produce. `-0` does happen `+0` or just `-` does never happen... (in other words we never accepted this, why should we start now?)

> Should we even allow `123.`? That feels more iffy to me than `.123`. We should definitely not allow `.`.

my first intuition was that `0.` looked more normal than `.123` but i have no strong opinion here.
My opinion here ist that we should define exactly one of these two as valid (because it makes the definition easier):

1. empty integer + dot + non empty digit sequence
2. non empty integer + dot + maybe empty digit sequence

**Comment by Tagl** [comment]
You can use the `+` format specifier to print integers with leading sign for both positive and negative numbers.
https://docs.python.org/3/library/string.html#format-specification-mini-language

**Comment by mpsijm** [comment]
> The spec says that the default output validator tries to compare floats [...] but does not define what a float is/which representation will be parsed as a float

> is there no definition of floating point numbers we could piggy back on (i.e. refer to)?

I wanted to say "Why not use the IEEE 754-2019 definition of the floating-point format?", but when reading the standard, I found that this standard does not explicitly define a grammar (though, funnily enough, it _does_ define a grammar for hexadecimal literals in section 5.12.3). I'll share my thoughts below and attempt to come up with a definition of floating points that is as close to the IEEE-definition as I can get :slightly_smiling_face: 

> we should not allow unnecessary stuff (like `+`)

But what if this is included in a standard way of formatting (like @Tagl mentioned) even without explicitly adding the `+` in the format specifier? For example, this is quite a standard way of formatting floats in Python, so I say that we should accept this:
```
>>> a = 1000
>>> f'{a:.1e}'
'1.0e+03'
```
This includes an extra `+` and leading zeroes in the exponent. As @niemela said, this may be a can of worms: if we want to allow "whatever 'normal' programming languages can print as output", I say we can better be as permissive as possible, and not unnecessarily restrict the syntax that we allow (as long as `std::stold` can read it).

> The `-` in `-0` is certainly unnecessary.

Also here, it may be unnecessary, but it is not guaranteed that it will never appear in a program's output. Even worse: the IEEE standard says in section 5.4.1: "The operation **squareRoot**(x) computes √x. It has a positive sign for all operands ≥0, except that **squareRoot**(−0) shall be −0." And indeed, when trying this in Python, the leading minus sign appears:
```
>>> a = -0 ** .5
>>> a
-0.0
>>> f'{a}'
'-0.0'
>>> f'{a:.1e}'
'-0.0e+00'
```

If we want to stick with allowing "anything that `std::stold` can read", we should define floating-points as: ([source](https://en.cppreference.com/w/cpp/string/basic_string/stof))

decimal floating-point expression. It consists of the following parts:
- (optional) plus or minus sign
- nonempty sequence of decimal digits optionally containing decimal-point character
- (optional) an exponent, containing:
	- `e` or `E`
	- optional minus or plus sign
	- nonempty sequence of decimal digits

Note that the "sequence of decimal digits" does not restrict leading zeroes, i.e. that means this definition would allow them, even when no "reasonable" programming language typically outputs them (unless you explicitly request them, of course: e.g. `f'{1:09.4f}'` outputs `'0001.0000'` in Python).

This very closely matches the (equally permissive) grammar for hexadecimal floating-point literals as defined in IEEE section 5.12.3. Converting this grammar to one that accepts _decimal_ floating-point literals, this would become something like:
```
sign         [+-]
digit        [0123456789]
expIndicator [Ee]
significand  ( {digit}* "." {digit}+ | {digit}+ "." | {digit}+ )
exponent     {expIndicator} {sign}? {digit}+
float        {sign}? {significand} {exponent}?
```

**Comment by evouga** [comment]
Does there need to be some restriction on the number of digits (in both the mantissa or exponent)?

**Comment by niemela** [comment]
Is there some reasonable way to test how much (if at all) this differs from the current implementations of Kattis and DOMjudge? Are there other existing implementations of the default validator that we should look at?

**Comment by mzuenni** [comment]
I would guess most implementations use `stold` or `sscanf` since mostly c++ is used and `from_chars` is not widely available for floats... Therefore, we mostly drop support for hexa decimal floats, INF and NAN

Regarding other implementations:
- There have been 3(?) versions of a default output validators for BAPCtools over the years.
- Domjudge, Kattis and BAPCtools all handle NAN and INF slightly different if i remember correctly...
- It's also worth looking at custom validators and to see how they handle floats. If this issue is solved custom validators can simply implement this to behave like the default output validator :) 
 - testlib.h uses `sscanf`
 - my own headers use `stold` or `from_chars`
 - checkers in python probably use this: https://docs.python.org/3/library/functions.html#float which does not allow hex but allows `_` as some kine of separator
 - java uses this: https://docs.oracle.com/javase/8/docs/api/java/lang/Float.html#valueOf-java.lang.String-
