### ISSUE TITLE
Add `packaged_by`

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#206]
Sometime the creator of a problem package is neither the `author` nor the `rights_owner`. It would be good to be able to record who created a package in those cases.

There are two obvious choices for how to do this:
1. Add (somethign like) `packager` to `credits` in `problem.yaml`.
2. Add `packaged_by` at the top level of `problem.yaml`.

I'm leaning towards option 2. I would argue that this information is more like `rights_owner` in that it should not typically be shown with credits, but is useful when reusing and or debugging a problem in the future.

Thoughts?

**Comment by Tagl** [comment]
Is this not `contributor`?

**Comment by niemela** [comment]
> Is this not `contributor`?

Maybe? `contributor` is the most generic of the `credit` options, so if we don't add this, than there's probably where it would fall.

What about these two (somewhat) hypothetical situations:

1. We want to upload some old problem pre-dating the problem format. Very little information exists, we have the statement and at least the sample data, but no strong data, no solutions, and no input validators. The person that creates a package for this would have to generate solutions and good data, so would certainly feel like a `contributor`.
2. We want to upload some old problem pre-dating the problem format. All the information exists. We have the problem statement, but maybe not in LaTeX, or maybe in LaTeX but using some things we don't typically use nowadays, so some minor editing is needed. We have strong data, and solutions. There would typically not be any input validators, that seems to not have been a thing (at least not a thing that was ever saved) before the problem format. The person that creates a package for this would have to do some light LaTeX edting, write a (very possibly trivial) input validator, and configure the package. Does that really rise to the level of `contributor`? I would feel a little but iffy in putting my name in if that's all I did?

If you think that either of those are not a `contributor` then we might need this. Even if both are, it could be useful to know who actually created the package as opposed to the stuff that was packaged.

**Comment by Tagl** [comment]
Sure, I see use for this in credits and I agree that (at least for pass-fail problems) that this is usually just an input validator and done. For scoring problems I do however tend to write partial solutions myself during packaging as they are often not part of the data that can be found.
