### ISSUE TITLE
Handle Sample output when `.ans` is not what we want to show

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#214]
Allow specifying a `.out` file for cases in `/sample`. When this exists, it will be used instead of `.ans` in the problem statement.

The reason for wanting to do this can be, e.g., because the output validator needs some secret information in the `.ans` or because we want "unreasonably" high precision in the `.ans` file.

When an `.out` file exists, it must be verified to pass validation.

**Comment by JoelNiemela** [comment]
Fixed by #226
