### ISSUE TITLE
Add place to store generators

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#216]
We have decided to not directly support generators in the format, and I think that's the right decision.

That said, problem authors quite often use generators, and when e.g. debugging a problem it is very useful to have access to whatever generator(s) was used.

The most common place to store these seems to be in `generators/` (which is were we were going to put it when we almost added it to the spec), followed by `gen/`, `generator.*`, `gen.*`, and `generator/`. They can also sometimes be found in `xtra/`, `tools/`, or `other/`.

I suggest we specify that generators should be stored in `generators/`, without any further requirements on how they should work. Maybe we should also suggest that `generators/README.*` should describe how to use them?

**Comment by Tagl** [comment]
We store them in the root of data 99.9% of times.

**Comment by niemela** [comment]
> We store them in the root of data 99.9% of times.

A yes, that too...
