### ISSUE TITLE
Notes from verdict aggregation discussion

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#234]
For pass-fail problems:
- Support testing `permitted` and `required` verdicts of sets of testcases (a single testcase, or leaves under a group).
- No testgroup/final verdict aggregation -- only permitted/required on sets of testcases can be asserted.
- **Question:** Do we indeed not need final verdict assertions?

For scoring problems:
- No verdict aggregation.
- Allow asserting permitted/required vertices of (sets of) test cases.
- Allow asserting scores of testcases/testgroups/final score.

**Comment by niemela** [comment]
> * **Question:** Do we indeed not need final verdict assertions?

I actually don't think we do.

> * No verdict aggregation

I really don't like this... but I'm not sure how much it matters?
