### ISSUE TITLE
Add a simple to encode raster grafics format

### ISSUE THREAD

**Issue by mzuenni** [Kattis/problem-package-format#24]
Right now `.png`, `.jpg`, and `.jpeg` are supported file types. However, encoding files of these types yourself is quite difficult due to compression and checksums. I would suggest to add a simpler format (like `.bmp`) which allows you to create raster images in any language you want without additional libraries.

**Comment by pehrsoderman** [comment]
Thank you for the suggestion. 

.bmp is a bit of a foot-gun. Image size tends to be large, and the support in LaTeX is not very good without lots of tricks.

You can easily convert bmp images to .png or .jpg with a tool like ImageMagic (https://imagemagick.org/script/convert.php) for use in a problem. 

Is there any specific usecase where converting to .png or .jpg is not an acceptable solution?

**Comment by niemela** [comment]
No (?), only the creator of the problem package needs to have the tool. What am I missing?

**Comment by mzuenni** [comment]
At NWERC and GCPC we use the `generator.yaml` and don't add testdata to the git, therefore everyone has to be able to generate the data.

**Comment by niemela** [comment]
Are you saying that you have generator programs that create the images on the fly?

What language are you using? I thought e.g. Python had pretty robust libraries for creating PNGs.

**Comment by niemela** [comment]
We think this might be part of the generator spec, we will discuss in that context. Closing this issue.
