### ISSUE TITLE
Should we backport the float definition to `legacy`?

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#267]
I.e. is 

> * All floating-point numbers (in any files, including in the problem package or submission output, that are parsed by contest system tools or the default output validator) must be given in decimal and may use scientific notation.
>   More specifically, floating-point numbers must satisfy the following grammar, which accepts formatted floating-point output from most major programming languages:
>   ```regex
>   sign         [+-]
>   digit        [0123456789]
>   expIndicator [Ee]
>   significand  ( {digit}* "." {digit}+ | {digit}+ "." | {digit}+ )
>   exponent     {expIndicator} {sign}? {digit}+
>   float        {sign}? {significand} {exponent}?
>   ```
> The systems parsing these floating-point numbers may impose reasonable limits on the number of digits, but must support at least 30 digits before and after the decimal point. They must use an internal representation with at least 52 bits of mantissa precision and should make a best effort to parse floating-point numbers to their closest representable values.

What we want `legacy` to specify?

**Comment by eldering** [comment]
> What we want `legacy` to specify?

I think we shouldn't try to backport it, because this specifcation is not going to be equal to what was actually supported. For future versions I think it's fine to say: this is what any tool should support (but it could support more), but I don't think that's great to backport to the legacy spec.

**Comment by niemela** [comment]
Sounds reasonable. Closing.
