### ISSUE TITLE
Add support for bad input

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#29]
Allow specifying of test data that must be failed by some input validator.

Suggested by @jsannemo.

**Comment by jsannemo** [comment]
**Decision**: `data/invalid_inputs`. Supports `input_validator_flags` in `testdata.yaml`:s

**Comment by RagnarGrootKoerkamp** [comment]
Groups and testdata.yaml's are also allowed inside `data/invalid_inputs`
