### ISSUE TITLE
Breaking change: problem-unique testcase names

### ISSUE THREAD

**Issue by thorehusfeldt** [Kattis/problem-package-format#32]
Testcases should have problem-unique names. Everything would be simpler.

**Comment by niemela** [comment]
How should this work with symlinks?

**Comment by jsannemo** [comment]
@pehrsoderman @ghamerly Opinions?

**Comment by pehrsoderman** [comment]
This sounds like a somewhat annoying limitation. It basically means that for many problems, you are going to see names for files like `sample/sample-01.in` and ´secret/secret-01.in´. I am not sure what would be simplified by this limitation. We already have detection of duplicate input files in problemtools.

**Comment by RagnarGrootKoerkamp** [comment]
@RagnarGrootKoerkamp to make a shell script to grep for occurrences of existing duplicate cases

**Comment by RagnarGrootKoerkamp** [comment]
There are ~hundreds of problems on kattis where `sample/1.in` overlaps with a distinct `secret/1.in`, so this seems not feasible, and it wouldn't give that much anyway.
