### ISSUE TITLE
Allow specifying something like "publicly available from"

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#343]
One piece of feedback I got at RCDS at ICPC when talking about the ICPC Problem Archive (which is one important user of the problem format) was a need to specify that a problem can't be made publicly available until some specific date.

**Comment by evouga** [comment]
As we discussed a bit in Astana, there are several ways to handle this feature, depending on what the stakeholders requesting this feature have in mind:

1. Something like an `embargo-until` key in `problem.yaml`, a polite suggestion to anyone handling the problem package not to distribute it further until the stated date.
2. Decorate the `license` with a date on which that license becomes effective. The polite suggestion is now legally binding, but there are some murky questions here: presumably the problem will appear on some contest before the "publicly available from" date. Do contest systems need a separate license for hosting the problem on that contest, and how is it communicated? Is the archive, contest system, and anyone else handling the problem before the "publicly available from" date exposing themselves to legal liability if they accidentally leak the problem? 
3. Do nothing; people simply shouldn't upload the package to an archive until they are ready for it to be distributed.

I have no strong opinions here---any of the above sounds reasonable, depending on what contributors and ICPC's lawyers want.

**Comment by eldering** [comment]
I don't think option 2 is very useful. Sure, maybe legally it's a bit stronger, but I think a simple `embargo-until` would be clearer and equally well respected.

However, I'd also lean towards 3: you should not upload it to an archive until an embargo is over, and up to that time I'd assume you can verbally inform any recipient of the package of the embargo date. How often would an embargo date lie more than a few weeks in the future and/or the package get distributed to more than a few trusted recipients?

**Comment by evouga** [comment]
I've heard that some of the ICPC regions want to delay publication of problems until an entire year after the contest date. In this case I can see the benefit of getting hold of the data right away vs. trying to hunt down people a year later.

**Comment by RagnarGrootKoerkamp** [comment]
Option 1 sounds reasonable to me. Codifying this information sounds useful.

**Comment by niemela** [comment]
> However, I'd also lean towards 3: you should not upload it to an archive until an embargo is over, and up to that time I'd assume you can verbally inform any recipient of the package of the embargo date. How often would an embargo date lie more than a few weeks in the future and/or the package get distributed to more than a few trusted recipients?

I strongly disagree with this. For one selfish reason, and for a good reason:

- Selfish: when we run contests on Kattis they are (by necessity) already uploaded to Kattis, which is also an archive.
- Good: for the ICPC Problem Archive we want to (arguably "must") be able to collect problems directly after the contests. Waiting for a year would not be acceptable.

**Comment by eldering** [comment]
Ok. I was assuming that embargoes would only last week(s), and TBH I don't think there's a good reason for it to be a year. But if that's what people want, then I guess option 1 it is.

**Comment by Tagl** [comment]
Do they have a (good or bad) reason for delaying the release for this (**extremely**) long time?
I think it's a good addition overall, but the length is worrying.
Hopefully nobody takes it to the same level as copyright duration.

**Comment by niemela** [comment]
> Do they have a (good or bad) reason for delaying the release for this (**extremely**) long time?

I think they might want to reuse the problems in lower level contests for a bit.
