### ISSUE TITLE
Add support for reading input from file or command line

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#37]
Maybe something like:

command line arguments are given in a file called `<test case>.args`, files available are put in a directory called `<test case>.files`.

**Comment by evouga** [comment]
Sounds good to me. `<test case>.args` is required to have exactly one line?

**Comment by Tagl** [comment]
Sounds good to me too.
`.args` files does not necessarily have to have one line, we could treat all whitespace the same.

**Comment by evouga** [comment]
From our discussion:
 - No, `<test case>.args` can have line breaks (each token gets passed in as an argument)
 - There should be a way to provide a tarball instead of a folder for `<test case>.files`
 - The output validator should have access to the folder in its state after the submission runs. Same for interactive problems in between interactions.

**Comment by eldering** [comment]
Do we really need this? What's the use case for reading from command line, where reading the same things from `stdin` is not acceptable?

**Comment by jsannemo** [comment]
I'm not 100% sold on this. You can get something pretty close to this by having a tar-file as `.in` and an interactive validator that extracts this into a file system.

I would very much prefer first seeing some actual problems on this format first, either using the above workaround and/or seeing an example implementation in problemtools+Kattis first. Not having this in the spec doesn't prevent anyone from implementing this, and having a few real-life example helps us understand whether this is actually needed and if this is the best way to do so.

**Comment by niemela** [comment]
> Do we really need this? What's the use case for reading from command line, where reading the same things from `stdin` is not acceptable?

It's more often useful in an educational setting. If reading from a file is the purpose, then reading the same thing from `stdin` is clearly not good enough.

That said, you can read files with random access, you can't do that with `stdin`.

**Comment by niemela** [comment]
> I'm not 100% sold on this. You can get something pretty close to this by having a tar-file as `.in` and an interactive validator that extracts this into a file system.

The overhead for that feels daunting (and kinda ugly).

**Comment by niemela** [comment]
This feature has been requested from Kattis several times. I would be *very* happy if it could be supported by the problem format.

**Comment by jsannemo** [comment]
> The overhead for that feels daunting (and kinda ugly).

I don't feel very daunted by it. It's a bit ugly yes, but so is adding too much stuff to the spec.

**Comment by jsannemo** [comment]
> This feature has been requested from Kattis several times. I would be _very_ happy if it could be supported by the problem format.

And nothing precludes Kattis from implementing this, adding a few those problems, and if we see that this is a good design, promote it into the spec.

**Comment by simonlindholm** [comment]
> You can get something pretty close to this by having a tar-file as .in and an interactive validator that extracts this into a file system.

Does the validator share file system with the submission? If not you have to do it using included code, which restricts you to a small set of languages (probably ok in an educational setting), and is hard to get right if you want the submission to use a normal main function.

**Comment by jsannemo** [comment]
> > You can get something pretty close to this by having a tar-file as .in and an interactive validator that extracts this into a file system.
> 
> Does the validator share file system with the submission? If not you have to do it using included code, which restricts you to a small set of languages (probably ok in an educational setting), and is hard to get right if you want the submission to use a normal main function.

We are discussing specifying running directories and so on in a way that allows a shared directory between an interactive validator and a submission.

**Comment by jsannemo** [comment]
> > You can get something pretty close to this by having a tar-file as .in and an interactive validator that extracts this into a file system.
> 
> Does the validator share file system with the submission? If not you have to do it using included code, which restricts you to a small set of languages (probably ok in an educational setting), and is hard to get right if you want the submission to use a normal main function.

We are discussing specifying running directories and so on in a way that allows a shared directory between an interactive validator and a submission.
