### ISSUE TITLE
Invalid sample files

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#40]
We had some problems with randomized solutions where we guarantee n=1000, but that is unpractical in teh samples, so we had those with much smaller n, eg n=10.

It would be nice to officially support samples that are only shown, but not run.

I implemented this with a `.{in,ans}.statement` extension, but open to other options.

**Comment by jsannemo** [comment]
Also, for judging you can use
`grader_flags: ignore_sample`

**Comment by RagnarGrootKoerkamp** [comment]
side note: this `grader_flags: ignore_sample` only works in `data/testdata.yaml` (the root one). For domjudge export, BAPCtools should simply not export the sample files.

**Comment by RagnarGrootKoerkamp** [comment]
`grader_flags: ignore_sample` has a different purpose after all (i.e. to run on samples but ignore results for grading/scoring), so dedicated support would be good.

**Comment by simonlindholm** [comment]
Also, #68 removes grader flag support for non-scoring problems

**Comment by niemela** [comment]
> I don't like this. You can already use input validator flags to specify that you want different limits for the sample group.

Closing based on this.

@RagnarGrootKoerkamp if you disagree please reopen, but also please explain why the above comment isn't right.

**Comment by RagnarGrootKoerkamp** [comment]
The goal is to show the samples, but never run them.

With `input_validator_flags`, you can modify the input validator to accept them, but then team submissions would still be run on them, which I want to avoid. (Since in the typical example we guarantee `n=10^5` in all secret cases, and then I don't want to run them with `n=10` on the samples.)

**Comment by Tagl** [comment]
Why is ignore_sample not sufficient for this?

**Comment by RagnarGrootKoerkamp** [comment]
I suppose running but excluding their verdict would indeed be sufficient. But then again, #68 removed grading flags for non-scoring problems :shrug:

**Comment by niemela** [comment]
I have a hard time understanding why it's a good idea to have a sample that is *so* "wrong" that it's important to make sure it never gets run?

In these previous cases, is there more to it then 10 != 1000, so technically the sample is not valid? I.e. is it somehow potentially hard to make a solution that handles the 1000 cases correctly to also be reasonably good at the 10 cases? Or is it that since you promise that n = 1000, you want to allow solutions to not even look at n (and maybe n is not even given), and if they have to sun on sample as well they would have to?

Do you have a suggested mechanism for doing this? It seems most natural to me to have some kind of flag in `testdata.yaml`?

(Note that if we find a mechanism that works here that could also be used for #126)

**Comment by simonlindholm** [comment]
> I.e. is it somehow potentially hard to make a solution that handles the 1000 cases correctly to also be reasonably good at the 10 cases?

This is not uncommon in my experience.

**Comment by RagnarGrootKoerkamp** [comment]
For randomized solutions problems can be easier for large n where edge cases are very unlikely, but they could fail on smaller samples.

A flag like `run_samples: false` in `data/testdata.yaml` sounds fine to me.

**Comment by niemela** [comment]
> A flag like `run_samples: false` in `data/testdata.yaml` sounds fine to me.

So, all or nothing is enough? (Well, maybe that's a moot question, because we could always add some of the samples to secret if we definitely want them to be run?)

Would `run_samples` only be allowed in the root `testdata.yaml` then?

**Comment by RagnarGrootKoerkamp** [comment]
- yes, all or nothing should be good enough for me. I suppose there is the hypothetical case where half of the samples should not be run and half should be run and the teams should get feedback for those, but that sounds too far fetched to support.
- yes, `run_samples` should only be in the root. I believe we already have other keys for which this is the case?

**Comment by niemela** [comment]
> * yes, all or nothing should be good enough for me. I suppose there is the hypothetical case where half of the samples should not be run and half should be run and the teams should get feedback for those, but that sounds too far fetched to support.

Agreed.

> * yes, `run_samples` should only be in the root. I believe we already have other keys for which this is the case?

No, I don't think we do (and I don't think we ever did), but that doesn't mean we can't.

**Comment by niemela** [comment]
It seems that we have at least some weak consensus on adding `run_samples` to `testdata.yaml`, and only allowing it in the root?

@RagnarGrootKoerkamp Do you want to make a draft PR, or should I?

**Comment by Tagl** [comment]
I have written a pull request here #141
