### ISSUE TITLE
Invalid interactive input files

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#41]
Interactive problems have a 'hidden' `.in` file that is never seen by contestants/submissions, only by the interactor. Nevertheless we can put a sample.in next to a sample.interaction to run the testcase as a sample, eg for separate judging feedback.

These sample.in files should not (always) be shown to contestants nor be available for download, since they are meaningless.

We often provide a small test interactor in the attachments/ directory, but that may follow a different spec for its input files, incompatible with the sample.in used by the interactor.

**Comment by jsannemo** [comment]
Isn't this what we just added into the spec?
