### ISSUE TITLE
Remove `show_test_data_groups`

### ISSUE THREAD

**Issue by jsannemo** [Kattis/problem-package-format#42]
Suggestion: remove `show_test_data_groups` and leave how to deal with this to the CCS.

**Comment by jsannemo** [comment]
Some rationale: This is essentially always true for scoring problems, and false for pass-fail problems.

Sometimes, contests might want to e.g. show sample results for their pass-fail problems, but sometimes they may not. This indicates that the right level for this setting might not actually be the problem but rather the contest and/or installed problem

**Comment by niemela** [comment]
I think this would make a lot of sense.

@pehrsoderman @austrin Thoughts?

**Comment by pehrsoderman** [comment]
I think removing it should be fine.

**Comment by jsannemo** [comment]
**Decision**: this is removed, and left to the CCS.
