### ISSUE TITLE
Drop scoring objective from problem.yaml

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#43]
The scoring/objective key in `problem.yaml` defaults to `max` and is always never anything else.

In theory a minimization problem could always be implemented as a maximization problem.

We should drop this setting.

The only problems currently on Kattis using minimization are:
https://baylor.kattis.com/problems/baylor.linearregression
https://baylor.kattis.com/problems/baylor.logisticregression
https://baylor.kattis.com/problems/baylor.gradientdescent
https://kth.kattis.com/problems/kth.adk.castingheuristic

**Comment by niemela** [comment]
@ghamerly You are the author (and main user) of 3 out of 4 of these. What's your opinion?

**Comment by ghamerly** [comment]
Actually, I have rewritten the first two problems to be maximization problems; they are no longer minimization problems. So it's only the gradient descent problem (of mine) that uses minimization.

I am okay with disallowing minimization.

**Comment by jsannemo** [comment]
**Decision**: remove this
