### ISSUE TITLE
Problem name in problem.yaml

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#48]
Should `name` actually be required?

We can (and do) get the name from `\problemname` in LaTeX. We could do something similar with Markdown.

How should we handle when the problem name is specified in both problem statement and `problem.yaml`?

**Comment by niemela** [comment]
@pehrsoderman @austrin @ghamerly

**Comment by pehrsoderman** [comment]
I think it makes sense to keep it, to have a canonical name for the problem. If you have multiple language statements for the problem they could have different names. Also, it is easier to parse the yaml with tooling, compared to the latex or markdown.

**Comment by RagnarGrootKoerkamp** [comment]
What we do in BAPCtools:
- Specify the name in `name:` in `problem.yaml` as a string.
- In `problem.en.tex` we do `\problemname{\problemyamlname}`, where `\problemyamlname` is the string name as specified in the yaml.
- In case of multiple natural languages, `\problemyamlname` in `problem.xy.tex` is replaced by the value of `xy` in the `name:` dictionary.
- In case you want a dedicated latex name, simply put that as `\problemname{Problem $i$}`.

How do you feel about adding this to the spec?

**Comment by RagnarGrootKoerkamp** [comment]
Alternatively, we could reuse the constants and have a 'magic constant' `XproblemnameX` that is replaced by the string (for the current language) specified in `problem.yaml`

**Comment by jsannemo** [comment]
I like the magic constant, it's very cross-language

**Comment by RagnarGrootKoerkamp** [comment]
New idea:
`\problemname` (or `\problemname{}`) renders the name as in the problem.yaml, and `\problemnam{\LaTeX name}` can be used to have a specific name that includes latex/math.

**Comment by niemela** [comment]
> New idea:
> `\problemname` (or `\problemname{}`) renders the name as in the problem.yaml, and `\problemname{\LaTeX name}` can be used to have a specific name that includes latex/math.

I think this is the way to go (and specifcially `\problemname{}`). This also allows systems that want to have a fancy LaTeX name to support that by parsing the LaTeX or Markdown. We should (maybe?) add a requirement that the name provided in `problem.yaml` should be an acceptable fallback to whatever is specified in `\problemname`.

There are only ~4 problemnames on Kattis that tries to use "fancy LaTeX" in the problem name:
- So you want to be a $2^n$-aire?
- Perfect $p$th Powers
- Perfect $k$-ary Tree
- $S$-Nim

Based on this, I think this would be fine.
