### ISSUE TITLE
Tooling to "export" a problem package for CCSs (e.g. DOMjudge)

### ISSUE THREAD

**Issue by evouga** [Kattis/problem-package-format#63]
Tooling is needed that will prepare problem packages for DOMjudge. It will need to:
 - compile the problem statements to PDF
 - compute time limit from the problem submissions and multipliers and sets `time_limit` accordingly
 - filter out test data that isn't used for judging
 - parse the default output validator's flags in `testdata.yaml` and convert them into a form DOMjudge understands
 
Other stuff?

**Comment by evouga** [comment]
@eldering @RagnarGrootKoerkamp

**Comment by nickygerritsen** [comment]
Cc @johnbrvc you might also be interested in this for pc^2

**Comment by jsannemo** [comment]
I can make the problem verification binary I'm writing be plugin-able so that all of this functionality could be a part of the domjudge problem import flow as well. @eldering @nickygerritsen

**Comment by nickygerritsen** [comment]
I'm not sure what Jaap thinks, but we could use it indeed to automate the 'export' so DOMjudge can import it if a PDF and/or timelimit is missing. But I think we should also still have the option to run the tool externally?

**Comment by RagnarGrootKoerkamp** [comment]
This is basically what `bt zip` does.

Note that we also have `bt export`, which directly imports it into a running server using the API.

**Comment by niemela** [comment]
Closing this because it's bit really part of the *format*, but also because work seems to already be underway in several tools.
