### ISSUE TITLE
Specification for interactive problems

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#7]
Doesn't have to be exhaustive, but should mention the basics:

- `.interaction` files for samples and its syntax
- Samples *do not* have a corresponding `.in` file. For BAPCtools I was assuming this, but it seems that at least @simonlindholm thinks otherwise. I agree that not putting a `.in` file makes sense.
- Testdata for the samples can be provided in e.g. `attachments/1.in`.
- `validation: custom interactive` for the `problem.yaml`
- `\begin{Interaction} ... \end{Interaction}` for problem statement

**Comment by simonlindholm** [comment]
> Samples do not have a corresponding .in file. For BAPCtools I was assuming this, but it seems that at least @simonlindholm thinks otherwise. I agree that not putting a .in file makes sense.

Example of a problem without .in: https://github.com/Kattis/problemtools/tree/develop/examples/guess/data/sample

**Comment by jsannemo** [comment]
Reviving this a bit...

`validation: custom interactive` is in the spec now.

Let's document `.interaction`.

Surely `.in` and `.ans` should be *allowed* in the spec. PO surfaces sample results in the UI, and showing how you did on the sample case presented in the statement could be valuable.

**Comment by RagnarGrootKoerkamp** [comment]
So, how about this:?

The `.interaction` is what is shown in the statement.

If a `.in` is present, that means submissions should be run on the sample, and the `.in` is fed to the interactor.
The `.in` should never be shown to contestants, since the interactor input is 'private'.

If a `.in` is present, an empty `.ans` must be present as well.
(Or alternatively, we forbid all `.ans` for interactive problems.)

**Comment by jsannemo** [comment]
Yes, I agree.

Why must .ans be empty? I understand it most often is, but I'm sure there has been at least one instance where we've used it in PO because there was some natural separation between input to the interactor and answer to compare with?

**Comment by RagnarGrootKoerkamp** [comment]
Ah yes you're right. The .ans could contain some hard-to-compute information that can help the interactor.

In that case `.ans` must always be present.

**Comment by jsannemo** [comment]
@RagnarGrootKoerkamp will you make a PR for this?

**Comment by RagnarGrootKoerkamp** [comment]
I think I'm too busy at the moment to do that; sorry

**Comment by niemela** [comment]
I consider this done after merging #22.

@jsannemo @RagnarGrootKoerkamp do you disagree?
