### ISSUE TITLE
Document behavior of appending to team/judge feedback

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#74]

**Comment by niemela** [comment]
@RagnarGrootKoerkamp Could you make a PR for this? Or elaborate a bit more?

**Comment by RagnarGrootKoerkamp** [comment]
Hmm, I *think* this had something to do with whether output validators should overwrite or append the feedback files, and whether they can expect them to exist or at least expect them to not have content written in them.

But I'm not quite sure anymore. @jsannemo @Tagl maybe?

**Comment by niemela** [comment]
@pehrsoderman Thoughts?

**Comment by Tagl** [comment]
My validators generally append but they're only ever really appending if I'm running them manually so they could just as well overwrite instead.

I print the whole teammessage.txt file for the user, and I do so for every single failed testcase that is run.
So there is one teammessage.txt per testcase.

I do the same for judgemessage.txt

**Comment by pehrsoderman** [comment]
The files should be fresh for each run. Assumptions that testcases are run in a specific ordering, and that there are state that can carry over from one testcase to the next seems pretty bad to me. 

So appending makes very little sense to me.

**Comment by niemela** [comment]
Closing this based on @pehrsoderman's comment. @RagnarGrootKoerkamp if you still feel that some part of this needs clarification, could you suggest wording?
