### ISSUE TITLE
Render difference between `-icpc` and full specification

### ISSUE THREAD

**Issue by thorehusfeldt** [Kattis/problem-package-format#79]
Currently there is no way to see which parts of the specification pertain to the ICPC subset short of reading HTML tags in the source. (Sometime, a pair of buttons in the left-hand margin enables this, but it’s fragile, implicit, and not obvious to outsiders.)

**Comment by RagnarGrootKoerkamp** [comment]
Right, after @niemela changed the css class to `not-icpc` the rendering broke. I'll fix the rendering and buttons. Whether we like them or not and/or want to move to readthedocs and/or separate pages for icpc and non-icpc subset can be discussed separately/after.

**Comment by niemela** [comment]
The radio buttons don't work for me. I see the full text, with the ICPC subset in red,regardless of what is chosen.

**Comment by RagnarGrootKoerkamp** [comment]
@thorehusfeldt what do you think of how it looks now?
See https://www.kattis.com/problem-package-format/spec/2023-07-draft.html

Note that the radio buttons are only shown on the actual spec pages, not on changelog and examples, where they are not needed.

**Comment by thorehusfeldt** [comment]
This is a clear improvement. (Maybe first paragraph, where the version number is stated, can also be explicit about what I’m seeing.)

**Comment by niemela** [comment]
Fixed by #91
