### ISSUE TITLE
Support per test case explanations

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#81]
See https://github.com/Kattis/problemtools/issues/21

**Comment by jsannemo** [comment]
I like the `\sample{<filebasename>}` and `\allSamples` command suggestion, with a default of "append all samples afterwards" behaviour.

**Comment by RagnarGrootKoerkamp** [comment]
I'd say the argument to `\sample{..}` should be a path relative to `data/sample`, without the `.in` extension.

I'd say that the default is that all samples are appended if `\sample` and `\allSamples` are not otherwise used. As soon as one of them is used, it is up to the user to ensure all samples are indeed rendered. (Tooling could warn/error if not, and/or we could require that all are used.)

**Comment by niemela** [comment]
@jsannemo @RagnarGrootKoerkamp Are either of you up to writing a PR for this?

**Comment by RagnarGrootKoerkamp** [comment]
When I have time at some point, yes, I can write a PR :)

**Comment by niemela** [comment]
> I'd say the argument to `\sample{..}` should be a path relative to `data/sample`, without the `.in` extension.

Agreed. This is what I would claim is the "name of the test case". It's not very well described as such in the spec.

**Comment by niemela** [comment]
> I'd say the argument to `\sample{..}` should be a path relative to `data/sample`, without the `.in` extension.

The "base name" of a test case has now been defined ([Here](https://github.com/Kattis/problem-package-format/blob/master/spec/2023-07-draft.md?plain=1#L354-L355)) such that the "base name" of the test case with input `1.in` in the sample directory is `sample/1`.

Reusing the "base name" seems like a good idea, but OTOH, all samples would have the prefix `sample/` which is a bit annoying.

Thoughts?

**Comment by niemela** [comment]
> I like the `\sample{<filebasename>}`

I think we have agreement on that. :+1:

> and `\allSamples` command suggestion, 

Why is that needed? Especially if we have the default below?

@mzuenni I think you originally suggested it, could you elaborate?

> with a default of "append all samples afterwards" behaviour.

Is this "append all samples afterwards if no `\sample` (or `\allSamples`) was used", or "append all remaining samples (i.e. ones that did not get a `\sample`) afterwards"?

It seems to me that we only need `\allSamples` *or* a good default, and I would prefer the latter.

How do we do the same in Markdown?

**Comment by RagnarGrootKoerkamp** [comment]
Some use cases:

```tex
\sample{1}
explain sample 1
\sample{2}
explain sample 2
```

```tex
\allSamples
Note that in the last sample, ...
```

```tex
\sample{1}
explanation
\sample{2}
\sample{3}
\sample{4}
```

I do agree something like automatically adding remaining samples at the end would be nice, and I don't think it'd be too hard to implement in BAPCtools:

Currently, we generate a file like below that is directly included where the samples should go.
```
\Sample{x/data/sample/1.in}{x/data/sample/1.ans}
\Sample{x/data/sample/2.in}{x/data/sample/2.ans}
\Sample{x/data/sample/3.in}{x/data/sample/3.ans}
```
Instead we could do something like:
```
\newcommand{\sample1}{\Sample{x/data/sample/1.in}{x/data/sample/1.ans}\renewcommand{\sample1}{}}
\newcommand{\sample2}{\Sample{x/data/sample/2.in}{x/data/sample/2.ans}\renewcommand{\sample2}{}}
\newcommand{\sample3}{\Sample{x/data/sample/3.in}{x/data/sample/3.ans}\renewcommand{\sample3}{}}
\newcommand{\remainingSamples}{\sample1\sample2\sample3}
```

**Comment by mzuenni** [comment]
It is meant to append all samples not used before.
And i would also implement useAll as useAllRemaining.

The useAll can also be useful if you first display all samples and then want to describe each sample

**Comment by niemela** [comment]
> The useAll can also be useful if you first display all samples and then want to describe each sample

Ah, I didn't think of that use case. Thanks!

**Comment by RagnarGrootKoerkamp** [comment]
Hmm; interesting suggestion.

While we typically number samples, it is also quite reasonable to name them like `zero-edge-case.in`, `unsorted-input.in`, and so in, in which case automatically inferring the sorted order could be a bit limited (even though that's already what happens now anyway).

I actually think it's good to force the user to be explicity about which sample goes where. When reading statements, reading `\sample{1}` is probably slightly more intuitive than just multiple `\sample` statements with some implicit behavior going on in the background.

(Also `\sample` will probably be slightly more annoying to implement nicely.)

**Comment by niemela** [comment]
> While we typically number samples, it is also quite reasonable to name them like `zero-edge-case.in`, `unsorted-input.in`, and so in, in which case automatically inferring the sorted order could be a bit limited (even though that's already what happens now anyway).

But, as you say, "automatically inferring the sorted order" is already what is specified. (And I *absolutely* think that we should *not* change that).

> I actually think it's good to force the user to be explicity about which sample goes where. 

That's fair. Do you think that it should be allowed to include the samples out of order? I think that would be really bad and confusing.

> When reading statements, reading `\sample{1}` is probably slightly more intuitive than just multiple `\sample` statements with some implicit behavior going on in the background.

I think we should use the full test case name when referring to test cases. If so the command would be `\sample{sample/1}` rather than `\sample{1}`.

> (Also `\sample` will probably be slightly more annoying to implement nicely.)

That's a good point. Is `\allSamples` (or as @Tagl pointed out, `\remainingSamples`) also annoying to implement?

How would you feel about having `\sample{<test case name>}` and `\remainingSamples` but requiring that samples are included in order?

**Comment by mzuenni** [comment]
> > When reading statements, reading \sample{1} is probably slightly more intuitive than just multiple \sample statements with some implicit behaviour going on in the background.
> 
> I think we should use the full test case name when referring to test cases. If so the command would be \sample{sample/1} rather than \sample{1}.

I think this is a bit redundant. `\sample` should only be able to include something from the sample directory anyway?

> > (Also \sample will probably be slightly more annoying to implement nicely.)
> 
> That's a good point. Is \allSamples (or as @Tagl pointed out, \remainingSamples) also annoying to implement?

I actually think that `\<next?>Sample` would be easier to implement. To make `\remainingSamples` work the tooling must already create a list sorted list of all testcases (since latex can not list all files in the `data/sample/` directory). Then the latex code only needs a counter as an index into that array (making `\remainingSamples` and `\<next?>Sample` easy).
On the other hand, if we give the name of the testcase we would still need that list and would likely do everything the same way except that we would also need additional code that checks if `#1 == SampleList[counter]`?

One additional remark: should `\sample` be aware of passes for multipass problems? i.e. do we want to be able to write per pass explanations?

**Comment by niemela** [comment]
> > I think we should use the full test case name when referring to test cases. If so the command would be \sample{sample/1} rather than \sample{1}.
> 
> I think this is a bit redundant. 

Yes, it's clearly redundant.

> `\sample` should only be able to include something from the sample directory anyway?

Absolutely.

> I actually think that `\<next?>Sample` would be easier to implement. To make `\remainingSamples` work the tooling must already create a list sorted list of all testcases (since latex can not list all files in the `data/sample/` directory). Then the latex code only needs a counter as an index into that array (making `\remainingSamples` and `\<next?>Sample` easy).
> On the other hand, if we give the name of the testcase we would still need that list and would likely do everything the same way except that we would also need additional code that checks if `#1 == SampleList[counter]`?

Ok, those are also good arguments :)

> One additional remark: should `\sample` be aware of passes for multipass problems? i.e. do we want to be able to write per pass explanations?

Great question! I don't think`\sample` needs to be multi-pass aware. I think showing the entire `.interaction` and adding the explanation after is good enough. (Also, it would be simpler).

**Comment by niemela** [comment]
B.t.w. I discussed test case explanations with @gitvanb (NA chief judge), he suggested having `<test case>.tex` files with the explanations instead. What do we think about that? (I believe I actually also suggested that earlier?)

**Comment by mzuenni** [comment]
where would the `<test case>.tex` be? next to the testcase or inside the `problem_statement` directory? what if I want to include an image as an explanation?

**Comment by niemela** [comment]
> where would the `<test case>.tex` be? next to the testcase or inside the `problem_statement` directory?

Correct.

> what if I want to include an image as an explanation?

Good point, that would kinda suck.
