### ISSUE TITLE
Are `keywords:` and `languages:` in `problem.yaml` lists or strings

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Kattis/problem-package-format#88]
The types of `keywords` and `languages` are `String or sequence of strings`, but then there is text

> Languages
> A space separated list of language code from the table in the overview section or all.
> If a list is given, the problem may only be solved using those languages.

'space separated list' is confusing in itself.

I've never used either of these so I don't know what is currently assumed. Either is fine, but we should be clearer.
(I think I have a slight preference for splitting a string on spaces, but an actual YAML list of keywords/languages is also good.)

note: `sequence` is YAML terminology for a list object

**Comment by Tagl** [comment]
I think it SHOULD be a list, but that is not how I implemented languages based on what the spec said.

**Comment by eldering** [comment]
I think it should be a YAML sequence (aka list). We should try to keep "manual" parsing by splitting on spaces to a minimum: use YAML for the syntactic stuff and the parsed YAML for the semantics.

**Comment by niemela** [comment]
The text in the table implies YAML sequences, the text below clearly specifies it as NOT that. The implementation in problemtools does NOT use YAML sequences (I think).

I would suggest that we "clarify" in `legacy` that it should be a space separated list (i.e. single string), and change it to YAML sequence in `2023-07-draft`.

**Comment by RagnarGrootKoerkamp** [comment]
I'll make a PR.

Currently `languages` also allows `all`. Is that used? Then it could be:
`languages: *"all" | <list of string>`
Alternatively `null` could be the default for `all` instead.

**Comment by niemela** [comment]
> Currently `languages` also allows `all`. Is that used?

Well, `languages` is barely used at all. Going into last weekend I was kinda hoping that we would come to the conclusion that we could just drop it completely. But @Tagl says that he is planning you use it significantly (?). I'm not *completely* convinced that there is a compelling use case.

One way to drop it would be to have `include` imply this. That's based on the assumption that `include` is the only reason to need `languages`. I'm not sure that that's true (but I think it is?). Maybe that's too hacky/ugly?

@Tagl could you elaborate a bit on how and why you wanted to use this so I can understand better?

> Alternatively `null` could be the default for `all` instead.

That's not the style we have used so far. We have typically used a special string (such as "all", "default" or similar) for the default "null-ish" value. I personally like that style.

**Comment by jsannemo** [comment]
I kind of like the option of providing include for e.g. IOI problems that have includes for Python and C++, without restricting the problem to those languages (since one can just as well do file I/O directly).

**Comment by niemela** [comment]
> I kind of like the option of providing include for e.g. IOI problems that have includes for Python and C++, without restricting the problem to those languages (since one can just as well do file I/O directly).

Right, I like that as well.

There are also the use case when you want to provide a library (say... parsing JSON) for some languages, but not all, since they already have it built in.

The "ugly hack" I referred to above is that in that case you could *also* have an empty "all" directory in your include. This would include *nothing* for all other languages, but would then allowed them (since they now have an (empty) include). It's a bit ugly, but it also allows us to drop a thing. I'm torn...
