### ISSUE TITLE
Is `type` a valid key in icpc subset?

### ISSUE THREAD

**Issue by thorehusfeldt** [Kattis/problem-package-format#93]
Can `type` be specified in icpc subset?

Because we write  
> Any unknown keys should be treated as an error.

This would make it an _error_ specify 

```yaml
type: pass-fail
```
in a `problem.yaml` that tries to conform to the spec.

The alternative is to enforce an _optional_ key with a singleton value
```cue
// icpc spec
type?: "pass-fail"
```
and allow in the full specification
```cue
// full spec
type?: *"pass-fail" | "scoring"
```
(Update after some head-scratching: this is not possible, at least in CUE, because of [actually good reasons]. See below.)

These things are not the same (because of the quoted passage above).

**Comment by thorehusfeldt** [comment]
A better way would be to _allow_ the boolean key:

```cue
scoring?: *false | true
```
only in the `-full`, and not even have the key in `-icpc`.

**Comment by RagnarGrootKoerkamp** [comment]
Same question here: How does `type: scoring` interact with `validation: scoring`? Does one imply the other? Do we need both? (@niemela?)

I agree that `scoring: bool` is nicer than `type:`.

**Comment by niemela** [comment]
@thorehusfeldt I agree on you analysis of the current situation.

I think we all (?) feel that it's bad that specifying `type: pass-fail` (if also verifying strictly ICPC subset) is an error.

I prefer the solution to write the ICPC spec ta have a `type` with a single allowed optional value `pass-fail` that is also the default. That seems to be best in line with what I think we mean by "subset".

I don't think that having a `scoring: bool` is better. I think it's less clear, and it makes "ICPC style" seem to be the "normal", and not one of two reasonable and "equal" choices.

**Comment by RagnarGrootKoerkamp** [comment]
If we go with `type:`, I'd allow  an optional `type: pass-fail` in ICPC-subset.

I don't think `scoring?: *false | true` says that 'non-scoring is more normal', just that scoring is something that needs to be enabled. (Which is already the case because you need `type: scoring` currently.)

**Comment by thorehusfeldt** [comment]
To make my position clear here:

I want
```cue
#problem_settings_icpc: {
    version: =~"^[0-9]+-[0-9]+(-icpc)(-draft)$" // allows 2023-07-icpc
    type?: *"pass-fail" | "scoring"
    if version =~ "icpc" { type?: "pass-fail" } // if icpc then type must be pass-fail or absent
   ... // more keys, see full schema
}
#problem_settings: {
    #problem_settings_icpc // embed all of the ICPC subset
    version !~ "icpc" // add the constraint that version cannot contain icpc
    // more keys, see full schema
}
```

**Comment by thorehusfeldt** [comment]
What I cannot give you (technically/logically because it breaks the model of what a schema extension is, but also because “what does subset mean” gets to the same conclusion):
```cue
#problem_settings_icpc: {
    type?: "pass-fail" // this works fine
   ... // more keys, see full schema
}
#problem_settings: {
    type: "pass-fail" | "scoring // ERROR: cannot undo a previous restriction of same key
    ... // more keys, see full schema
}
```

**Comment by thorehusfeldt** [comment]
Decided in [d8b4311](https://github.com/Kattis/problem-package-format/pull/45/commits/d8b43117ea62f89c0e6978ddbbc2f2e000d356f4).

There is now

#problem_settings_icpc: {
  ...
 `type?: "pass-fail"
 ...
}
so the key is _allowed_ but its value can only ever be `"pass-fail"`. Also, in `#problem_settings_icpc`, you can never set `validator.grading`.

I think this is almost as clean as I’d like it to be, backwards-compatible, quite readable, and (in particular) _works_.
